CREATE OR REPLACE PROCEDURE VER_TRABAJADOR(INTRO_DNI IN TRABAJADOR.DNI%TYPE, TRAB_SAL out TRABAJADOR%ROWTYPE)

AS
CURSOR TRAB_CURSOR IS
SELECT * FROM emple
WHERE DNI=INTRO_DNI;
TRAB_SAL TRABAJADOR%ROWTYPE;
BEGIN
    OPEN c1;
    FETCH c1 INTO TRAB_SAL;
       EXIT WHEN TRAB_CURSOR%NOTFOUND;
               
    CLOSE c1;
end;

