create or replace PROCEDURE listacentros(NOMBRE OUT SYS_REFCURSOR) AS
    BEGIN
        OPEN NOMBRE FOR
        SELECT "A1"."NOMBRE" "NOMBRE" FROM "PROYECTOFINAL"."CENTRO" "A1";
    CLOSE NOMBRE;
END;