/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Excepciones.AforoNoValido;
import Excepciones.CampoVacio;
import Excepciones.FechaNoValida;
import Excepciones.HorasNoValidas;
import Excepciones.NombreNoValido;
import Modelo.BD.CentroBD;
import Modelo.BD.tAdministradorBD;
import himevico2.controladora;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Iker
 */
public class panelCentro extends javax.swing.JFrame {

    /**
     * Creates new form Centro
     */
    
      private static String operacion;
       public panelCentro(String operacion) {
            this.operacion = operacion;
        initComponents();
          setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tcalleC = new javax.swing.JTextField();
        tnumeroC = new javax.swing.JTextField();
        ttlfC = new javax.swing.JTextField();
        tcodpostalC = new javax.swing.JTextField();
        tnombreC = new javax.swing.JTextField();
        tciudadC = new javax.swing.JTextField();
        tprovinciaC = new javax.swing.JTextField();
        baceptarC = new javax.swing.JButton();
        bsalirC = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(320, 320));
        getContentPane().setLayout(null);

        jLabel1.setText("CENTRO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(154, 18, 52, 16);

        jLabel2.setText("Calle");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 82, 31, 16);

        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(51, 44, 50, 16);

        jLabel4.setText("Numero");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(51, 165, 50, 16);

        jLabel5.setText("Provincia");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(44, 138, 57, 16);

        jLabel6.setText("Ciudad");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(57, 110, 44, 16);

        jLabel7.setText("Telefono");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(46, 235, 55, 16);

        jLabel8.setText("Cod Postal");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(34, 202, 67, 16);
        getContentPane().add(tcalleC);
        tcalleC.setBounds(125, 77, 134, 26);

        tnumeroC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnumeroCActionPerformed(evt);
            }
        });
        getContentPane().add(tnumeroC);
        tnumeroC.setBounds(125, 165, 140, 26);
        getContentPane().add(ttlfC);
        ttlfC.setBounds(125, 230, 140, 26);
        getContentPane().add(tcodpostalC);
        tcodpostalC.setBounds(125, 197, 140, 26);

        tnombreC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnombreCActionPerformed(evt);
            }
        });
        getContentPane().add(tnombreC);
        tnombreC.setBounds(125, 39, 134, 26);

        tciudadC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tciudadCActionPerformed(evt);
            }
        });
        getContentPane().add(tciudadC);
        tciudadC.setBounds(125, 105, 140, 26);
        getContentPane().add(tprovinciaC);
        tprovinciaC.setBounds(125, 133, 140, 26);

        baceptarC.setText("Aceptar");
        baceptarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baceptarCActionPerformed(evt);
            }
        });
        getContentPane().add(baceptarC);
        baceptarC.setBounds(74, 262, 92, 29);

        bsalirC.setText("Salir");
        bsalirC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsalirCActionPerformed(evt);
            }
        });
        getContentPane().add(bsalirC);
        bsalirC.setBounds(220, 260, 75, 29);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/imagenes/arenaG.jpeg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tnumeroCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnumeroCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnumeroCActionPerformed

    private void tciudadCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tciudadCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tciudadCActionPerformed

    private void tnombreCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnombreCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnombreCActionPerformed

    private void baceptarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baceptarCActionPerformed
        // TODO add your handling code here:
         if (operacion.compareTo("bajaC")== 0)
       {
           doBaja();
       }
       else
           if (operacion.compareTo("modificarC")== 0)
           {
               doModificar();
           }
           else
               doAlta();
    }//GEN-LAST:event_baceptarCActionPerformed

    private void bsalirCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsalirCActionPerformed
        // TODO add your handling code here:
        controladora.acabarV();
    }//GEN-LAST:event_bsalirCActionPerformed
  private void doModificar()
    { 
        try{
           if (datosCorrectos())
           {
             javax.swing.JOptionPane.showMessageDialog(this,"Datos correctos. Vamos a grabar los cambios");
             controladora.modificarC(tnombreC.getText(),tcalleC.getText(),Integer.parseInt(tnumeroC.getText()),Integer.parseInt( tcodpostalC.getText()),tciudadC.getText(),tprovinciaC.getText(),Integer.parseInt(ttlfC.getText()));
            
           }
       }
       catch(Exception e)
       {
         javax.swing.JOptionPane.showMessageDialog(this,"Problemas modificar "+e.getClass());
       }
}
    private void doBaja(){
        String nombre="";
        nombre=JOptionPane.showInputDialog(null,"Nombre del Centro a eliminar?");
       try{
             int respuesta = javax.swing.JOptionPane.showConfirmDialog(this,"¿ Estas segur@?");
             if (respuesta == 0)
             CentroBD.bajaCentro(nombre);
          
       }
       catch(Exception e)
       {
         javax.swing.JOptionPane.showMessageDialog(this,"Problemas con la baja "+e.getClass());
       }
    }
    
    private void doAlta(){
        try
        {
           if (datosCorrectos())
           {
             javax.swing.JOptionPane.showMessageDialog(this,"Datos correctos. Vamos a insertar en la base de  datos");
           controladora.subirCentro(tnombreC.getText(),tcalleC.getText(),Integer.parseInt(tnumeroC.getText()),Integer.parseInt( tcodpostalC.getText()),tciudadC.getText(),tprovinciaC.getText(),Integer.parseInt(ttlfC.getText()));
             
           }
       }
       catch(Exception e)
       {
         javax.swing.JOptionPane.showMessageDialog(this,"Problemas con el alta "+e.getClass());
       }
    }
   private boolean datosCorrectos(){
        try{
            validarNombre();
          
            validartelefono();
          
            return true;
        }
        catch(CampoVacio e)
        {
            javax.swing.JOptionPane.showMessageDialog(this,e.getMensaje());
            return false;
        }
        
        catch(Exception e)
        {
            javax.swing.JOptionPane.showMessageDialog(this,"Problemas validando los datos de entrada");
            return false;
        }
    }
    
    private void validarNombre()throws Exception{
        String nombre = tnombreC.getText();
        if (nombre.isEmpty())
            throw new CampoVacio("El nombre del CENTRO es un dato obligatorio");
       
       
       
    }
 
    private void validartelefono()throws Exception{
        String nombre=ttlfC.getText();
        if (nombre.isEmpty())
            throw new CampoVacio("El telefono debe ser de un maximo de 10 digitos");
        
                         nombre=nombre.toUpperCase();
                          Pattern n=Pattern.compile("[0-9]{10}");
                          Matcher m= n.matcher(nombre);
          }
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panelCentro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panelCentro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panelCentro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panelCentro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panelCentro(operacion).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton baceptarC;
    private javax.swing.JButton bsalirC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tcalleC;
    private javax.swing.JTextField tciudadC;
    private javax.swing.JTextField tcodpostalC;
    private javax.swing.JTextField tnombreC;
    private javax.swing.JTextField tnumeroC;
    private javax.swing.JTextField tprovinciaC;
    private javax.swing.JTextField ttlfC;
    // End of variables declaration//GEN-END:variables
}
